sumup-data-bigquery:
  target: dev
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: sumup-raw
      schema: schema
      threads: 2
      type: bigquery
